# Generated by Django 5.2.17 on 2026-08-24 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Codigo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('areas', models.CharField(blank=True, max_length=200, verbose_name='Areas')),
                ('risk', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=10, verbose_name='Riesgo')),
                ('status', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('APROBADO', 'Aprobado'), ('EN_DESARROLLO', 'En desarrollo'), ('EN_PRUEBAS', 'En pruebas'), ('LISTO_PARA_DEPLOY', 'Listo para deploy'), ('DESPLEGADO', 'Desplegado'), ('CERRADO', 'Cerrado'), ('RECHAZADO', 'Rechazado')], db_index=True, max_length=20, verbose_name='Estado')),
                ('opened_on', models.DateField(verbose_name='Fecha de apertura')),
                ('document_path', models.CharField(blank=True, max_length=300, verbose_name='Expediente')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Ultima sincronizacion')),
            ],
            options={
                'verbose_name': 'Control de cambio',
                'verbose_name_plural': 'Controles de cambio',
                'ordering': ['-code'],
                'permissions': [('sign_changecontrol', 'Puede firmar controles de cambio'), ('revoke_changecontrolsignature', 'Puede revocar firmas')],
            },
        ),
        migrations.CreateModel(
            name='ChangeControlSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('REQUISITO', 'Requisito aprobado'), ('RIESGO_PRUEBAS', 'Riesgo y pruebas aprobados'), ('RESULTADO', 'Resultado funcional aceptado'), ('DEPLOY', 'Autorizacion de deploy')], max_length=20, verbose_name='Decision')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de firma')),
                ('signed_name', models.CharField(default='', max_length=150, verbose_name='Nombre al firmar')),
                ('signed_initials', models.CharField(default='', max_length=60, verbose_name='Sumilla')),
                ('signed_identification', models.CharField(default='', max_length=30, verbose_name='Cedula al firmar')),
                ('meaning', models.TextField(help_text='Lo que la persona declaro al firmar, congelado en ese momento.', verbose_name='Significado')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Origen')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocacion')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='Motivo de la revocacion')),
                ('change_control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='changecontrol.changecontrol', verbose_name='Cambio')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_control_revocations', to=settings.AUTH_USER_MODEL, verbose_name='Revocada por')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_control_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Firmado por')),
            ],
            options={
                'verbose_name': 'Firma de control de cambio',
                'verbose_name_plural': 'Firmas de control de cambio',
                'ordering': ['change_control__code', 'decision', '-signed_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('change_control', 'decision'), name='uniq_firma_vigente_por_decision')],
            },
        ),
    ]
