# Generated by Django 5.2.17 on 2026-08-26 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventbus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('system', models.CharField(choices=[('ERP', 'ERP'), ('BI', 'BI / analitica'), ('API', 'API externa'), ('B22', 'B22'), ('OTHER', 'Otro')], default='ERP', max_length=20, verbose_name='Sistema')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Salida'), ('INBOUND', 'Entrada'), ('BIDIRECTIONAL', 'Entrada y salida')], default='OUTBOUND', max_length=20, verbose_name='Direccion')),
                ('transport', models.CharField(choices=[('LOG', 'Solo registrar'), ('HTTP', 'HTTP POST')], default='LOG', help_text='LOG deja el mensaje registrado sin salir; HTTP lo envia de verdad.', max_length=10, verbose_name='Transporte')),
                ('endpoint', models.URLField(blank=True, verbose_name='Endpoint')),
                ('auth_header', models.CharField(blank=True, help_text='Nombre de la cabecera (ej: Authorization).', max_length=60, verbose_name='Cabecera de autenticacion')),
                ('auth_token', models.CharField(blank=True, max_length=200, verbose_name='Token')),
                ('inbound_token', models.CharField(blank=True, help_text='Credencial que el sistema externo usa para empujar datos.', max_length=64, verbose_name='Token de entrada')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=15, verbose_name='Timeout (s)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Intentos maximos')),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=60, help_text='Se multiplica por el numero de intento.', verbose_name='Espera entre intentos (s)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conector',
                'verbose_name_plural': 'Conectores',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Salida'), ('INBOUND', 'Entrada')], default='OUTBOUND', max_length=20, verbose_name='Direccion')),
                ('field_map', models.JSONField(blank=True, default=dict, help_text='Destino: origen. Ej: {"orderNo": "unit", "workCenter": "station"}', verbose_name='Mapeo de campos')),
                ('static_fields', models.JSONField(blank=True, default=dict, help_text='Valores constantes que el receptor exige.', verbose_name='Campos fijos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='connect.connector', verbose_name='Conector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(blank=True, help_text='Que evento del bus dispara este envio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connector_contracts', to='eventbus.eventtype', verbose_name='Tipo de evento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['connector__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=180, unique=True, verbose_name='Identificador externo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Carga recibida')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSED', 'Procesado'), ('REJECTED', 'Rechazado')], db_index=True, default='RECEIVED', max_length=20, verbose_name='Estado')),
                ('result_detail', models.TextField(blank=True, verbose_name='Detalle')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound', to='connect.connector', verbose_name='Conector')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound', to='connect.connectorcontract', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de entrada',
                'verbose_name_plural': 'Mensajes de entrada',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField(verbose_name='Desde')),
                ('date_to', models.DateField(verbose_name='Hasta')),
                ('expected_count', models.PositiveIntegerField(default=0, verbose_name='Eventos esperados')),
                ('queued_count', models.PositiveIntegerField(default=0, verbose_name='Mensajes encolados')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Mensajes enviados')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Mensajes fallidos')),
                ('missing_keys', models.JSONField(blank=True, default=list, verbose_name='Eventos sin mensaje')),
                ('ran_at', models.DateTimeField(auto_now_add=True, verbose_name='Ejecutado')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='connect.connector', verbose_name='Conector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliacion',
                'verbose_name_plural': 'Reconciliaciones',
                'ordering': ['-ran_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=180, unique=True, verbose_name='Clave de idempotencia')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Cuerpo enviado')),
                ('status', models.CharField(choices=[('QUEUED', 'En cola'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('DISCARDED', 'Descartado')], db_index=True, default='QUEUED', max_length=20, verbose_name='Estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Proximo intento')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Codigo de respuesta')),
                ('response_body', models.TextField(blank=True, verbose_name='Respuesta')),
                ('last_error', models.TextField(blank=True, verbose_name='Ultimo error')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound', to='connect.connector', verbose_name='Conector')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound', to='connect.connectorcontract', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='eventbus.domainevent', verbose_name='Evento origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de salida',
                'verbose_name_plural': 'Mensajes de salida',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='connect_out_status_idx')],
            },
        ),
    ]
