# Generated by Django 5.2.17 on 2026-08-26 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0010_plant_plantarea_productionmeasurement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador estable del evento (ej: produccion.unidad.completada).', max_length=80, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('domain', models.CharField(choices=[('PRODUCTION', 'Produccion'), ('WAREHOUSE', 'Almacen'), ('CONNECTIVITY', 'Conectividad'), ('QUALITY', 'Calidad'), ('SYSTEM', 'Sistema')], default='PRODUCTION', max_length=20, verbose_name='Dominio')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('payload_keys', models.JSONField(blank=True, default=list, help_text='Lista de claves que el consumidor puede dar por seguras.', verbose_name='Claves esperadas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de evento',
                'verbose_name_plural': 'Tipos de evento',
                'ordering': ['domain', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('domain', models.CharField(blank=True, choices=[('PRODUCTION', 'Produccion'), ('WAREHOUSE', 'Almacen'), ('CONNECTIVITY', 'Conectividad'), ('QUALITY', 'Calidad'), ('SYSTEM', 'Sistema')], help_text='Filtro usado cuando la suscripcion no apunta a un tipo puntual.', max_length=20, verbose_name='Dominio')),
                ('handler', models.CharField(choices=[('INDICATORS', 'Recalcular indicadores'), ('LEDGER', 'Registrar en bitacora'), ('OUTBOUND', 'Publicar hacia afuera')], default='LEDGER', max_length=20, verbose_name='Manejador')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Intentos maximos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(blank=True, help_text='Vacio escucha todos los eventos del dominio elegido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='eventbus.eventtype', verbose_name='Tipo de evento')),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(help_text='Derivada del hecho origen (ej: unitstationevent:1234).', max_length=160, unique=True, verbose_name='Clave de idempotencia')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ocurrido')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publicado')),
                ('source_module', models.CharField(blank=True, max_length=40, verbose_name='Modulo origen')),
                ('aggregate_type', models.CharField(blank=True, help_text='Sobre que entidad ocurre el hecho (unidad, material, gateway).', max_length=40, verbose_name='Tipo de agregado')),
                ('aggregate_id', models.CharField(blank=True, max_length=120, verbose_name='Identificador del agregado')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Carga')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Publicado'), ('DISCARDED', 'Descartado')], default='PUBLISHED', max_length=20, verbose_name='Estado')),
                ('detail', models.TextField(blank=True, verbose_name='Detalle')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_events', to='assembly.assemblyline', verbose_name='Linea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='eventbus.eventtype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('planned_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minutos planificados')),
                ('downtime_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minutos de paro')),
                ('completed_units', models.PositiveIntegerField(default=0, verbose_name='Unidades completadas')),
                ('first_pass_units', models.PositiveIntegerField(default=0, verbose_name='Unidades sin falla')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Fallas')),
                ('rework_count', models.PositiveIntegerField(default=0, verbose_name='Retrabajos')),
                ('availability_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Disponibilidad %')),
                ('performance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rendimiento %')),
                ('quality_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Calidad %')),
                ('oee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='OEE %')),
                ('fpy_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='FPY %')),
                ('mtbf_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MTBF (min)')),
                ('mttr_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MTTR (min)')),
                ('event_count', models.PositiveIntegerField(default=0, verbose_name='Eventos considerados')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Calculado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_snapshots', to='assembly.assemblyline', verbose_name='Linea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador diario',
                'verbose_name_plural': 'Indicadores diarios',
                'ordering': ['-date', 'line__code'],
            },
        ),
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DELIVERED', 'Entregado'), ('FAILED', 'Fallido'), ('SKIPPED', 'Omitido')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('last_error', models.TextField(blank=True, verbose_name='Ultimo error')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='eventbus.domainevent', verbose_name='Evento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='eventbus.eventsubscription', verbose_name='Suscripcion')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', 'id'], name='eventbus_delivery_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'subscription'), name='eventbus_delivery_once')],
            },
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='event_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='event_aggregate_idx'),
        ),
        migrations.AddConstraint(
            model_name='indicatorsnapshot',
            constraint=models.UniqueConstraint(fields=('line', 'date'), name='eventbus_snapshot_unique'),
        ),
    ]
