# Generated by Django 5.2.17 on 2026-08-24 11:38

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_users', models.PositiveIntegerField(default=1)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['max_users'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='tenants.plan'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='Documento de identidad. Se guarda sin guiones ni espacios.', max_length=30, unique=True, verbose_name='Cedula o documento')),
                ('phone', models.CharField(max_length=30, verbose_name='Celular')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='TenantHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(choices=[('up', 'Disponible'), ('down', 'Con error'), ('unknown', 'Desconocido'), ('skipped', 'Omitido')], default='unknown', max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=63)),
                ('status_value', models.CharField(blank=True, max_length=32)),
                ('error', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Chequeo de salud de tenant',
                'verbose_name_plural': 'Chequeos de salud de tenant',
                'ordering': ('-checked_at',),
                'indexes': [models.Index(fields=['tenant', '-checked_at'], name='tenants_ten_tenant__370f96_idx'), models.Index(fields=['state', '-checked_at'], name='tenants_ten_state_429132_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de empresa',
                'verbose_name_plural': 'Membresías de empresa',
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('pos', 'Punto de venta'), ('wms', 'Gestión de bodegas'), ('migration_hub', 'Migración masiva'), ('qa_reception', 'Control de calidad en recepción'), ('qa_returns', 'Control de calidad en devoluciones'), ('qa_dispatch', 'Trazabilidad de lotes en salidas'), ('arcsa_enforcement', 'Control de dispositivos médicos'), ('manufacturing_qa', 'Control de calidad en producción'), ('recall_module', 'Retiros de mercado'), ('wms_putaway', 'Bodegas - ubicación dirigida'), ('wms_replenishment', 'Bodegas - alertas de reabastecimiento'), ('wms_tasks', 'Bodegas - tareas operativas'), ('wms_zone_picking', 'Bodegas - preparación por zona'), ('technovigilance', 'Tecnovigilancia (ISO 14971 / ARCSA)'), ('after_sales_service', 'Servicio post-venta / instalaciones'), ('iso_13485', 'ISO 13485 - Dispositivos médicos (compatibilidad)')], max_length=50, verbose_name='Módulo')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Módulo del tenant',
                'verbose_name_plural': 'Módulos del tenant',
                'ordering': ['tenant', 'module'],
                'unique_together': {('tenant', 'module')},
            },
        ),
    ]
