# Generated by Django 5.2.17 on 2026-08-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edgecommand',
            options={'ordering': ['-issued_at', '-id'], 'verbose_name': 'Comando a planta', 'verbose_name_plural': 'Comandos a planta'},
        ),
        migrations.AlterModelOptions(
            name='edgedevice',
            options={'ordering': ['gateway__code', 'code'], 'verbose_name': 'Dispositivo conectado', 'verbose_name_plural': 'Dispositivos conectados'},
        ),
        migrations.AlterModelOptions(
            name='edgegateway',
            options={'ordering': ['code'], 'verbose_name': 'Gateway', 'verbose_name_plural': 'Gateways'},
        ),
        migrations.AlterModelOptions(
            name='edgesignal',
            options={'ordering': ['-captured_at', '-id'], 'verbose_name': 'Senal de equipo', 'verbose_name_plural': 'Senales de equipo'},
        ),
    ]
