# Generated by Django 5.2.17 on 2026-08-26 04:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Recepcion')),
                ('supplier_name', models.CharField(blank=True, max_length=180, verbose_name='Proveedor')),
                ('container_number', models.CharField(blank=True, max_length=80, verbose_name='Contenedor')),
                ('asn_reference', models.CharField(blank=True, max_length=120, verbose_name='ASN / referencia externa')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de recepcion')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_receipts', to='core.location', verbose_name='Ubicacion destino')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepcion CKD',
                'verbose_name_plural': 'Recepciones CKD',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('traceability', models.CharField(choices=[('NONE', 'Sin trazabilidad'), ('LOT', 'Por lote'), ('SERIAL', 'Por serie')], default='NONE', max_length=20, verbose_name='Trazabilidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_materials', to='core.unit', verbose_name='Unidad base')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InboundReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Cantidad esperada')),
                ('received_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Cantidad recibida')),
                ('lot_number', models.CharField(blank=True, max_length=120, verbose_name='Lote')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.inboundreceipt', verbose_name='Recepcion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='wms.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Linea de recepcion',
                'verbose_name_plural': 'Lineas de recepcion',
                'ordering': ['receipt', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de material',
                'verbose_name_plural': 'Categorias de material',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='wms.materialcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='MaterialLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=120, verbose_name='Numero de lote')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='wms.material', verbose_name='Material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de material',
                'verbose_name_plural': 'Lotes de material',
                'ordering': ['material__code', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=120, verbose_name='Numero de serie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='wms.materiallot', verbose_name='Lote')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='wms.material', verbose_name='Material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serie de material',
                'verbose_name_plural': 'Series de material',
                'ordering': ['material__code', 'number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Recepcion'), ('TRANSFER', 'Traslado'), ('STATUS_CHANGE', 'Cambio de estado'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('ADJUSTMENT_OUT', 'Ajuste negativo')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad')),
                ('source_state', models.CharField(blank=True, choices=[('AVAILABLE', 'Disponible'), ('QUARANTINE', 'Cuarentena'), ('BLOCKED', 'Bloqueado'), ('IN_TRANSIT', 'En transito'), ('SCRAP', 'Baja')], max_length=20, verbose_name='Estado origen')),
                ('destination_state', models.CharField(blank=True, choices=[('AVAILABLE', 'Disponible'), ('QUARANTINE', 'Cuarentena'), ('BLOCKED', 'Bloqueado'), ('IN_TRANSIT', 'En transito'), ('SCRAP', 'Baja')], max_length=20, verbose_name='Estado destino')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia externa')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name='Motivo')),
                ('moved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/hora')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_inventory_movements', to='core.location', verbose_name='Ubicacion destino')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='wms.inboundreceiptline', verbose_name='Linea de recepcion')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_inventory_movements', to='core.location', verbose_name='Ubicacion origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='wms.material', verbose_name='Material')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='wms.materiallot', verbose_name='Lote')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='wms.materialserial', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('QUARANTINE', 'Cuarentena'), ('BLOCKED', 'Bloqueado'), ('IN_TRANSIT', 'En transito'), ('SCRAP', 'Baja')], default='AVAILABLE', max_length=20, verbose_name='Estado')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Cantidad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='core.location', verbose_name='Ubicacion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='wms.material', verbose_name='Material')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='wms.materiallot', verbose_name='Lote')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='wms.materialserial', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Saldo de inventario',
                'verbose_name_plural': 'Saldos de inventario',
                'ordering': ['material__code', 'location__warehouse__code', 'location__code', 'state', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WmsLocationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operational_type', models.CharField(choices=[('STORAGE', 'Almacenamiento'), ('RECEIVING', 'Recepcion'), ('SUPERMARKET', 'Supermercado'), ('LINE_SIDE', 'Line side'), ('QUARANTINE', 'Cuarentena'), ('DISPATCH', 'Despacho')], default='STORAGE', max_length=20, verbose_name='Tipo operativo')),
                ('allows_mixed_materials', models.BooleanField(default=True, verbose_name='Permite materiales mixtos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wms_profile', to='core.location', verbose_name='Ubicacion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil WMS de ubicacion',
                'verbose_name_plural': 'Perfiles WMS de ubicacion',
                'ordering': ['location__warehouse__code', 'location__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='materiallot',
            constraint=models.UniqueConstraint(fields=('material', 'number'), name='wms_lot_material_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='materialserial',
            constraint=models.UniqueConstraint(fields=('material', 'number'), name='wms_serial_material_number_uq'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['material', 'moved_at'], name='wms_move_material_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'moved_at'], name='wms_move_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['material', 'location', 'state'], name='wms_balance_material_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['serial'], name='wms_balance_serial_idx'),
        ),
    ]
