# Generated by Django 5.2.17 on 2026-08-26 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0010_plant_plantarea_productionmeasurement_and_more'),
        ('core', '0001_initial'),
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RELEASED', 'Liberado'), ('READY', 'Completo'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_kits', to='core.location', verbose_name='Ubicacion de entrega')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_kits', to='assembly.productionplan', verbose_name='Plan de produccion')),
                ('serialized_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_kits', to='assembly.serializedunit', verbose_name='Unidad serializada')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_kits', to='assembly.assemblystation', verbose_name='Estacion de entrega')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kit de linea',
                'verbose_name_plural': 'Kits de linea',
                'ordering': ['-created_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyKitLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad requerida')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.assemblykit', verbose_name='Kit')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_lines', to='wms.material', verbose_name='Material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linea de kit',
                'verbose_name_plural': 'Lineas de kit',
                'ordering': ['kit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PickMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RELEASED', 'Liberada'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_missions_to', to='core.location', verbose_name='Ubicacion destino')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_missions', to='wms.assemblykit', verbose_name='Kit')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_missions_from', to='core.location', verbose_name='Ubicacion origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mision de picking',
                'verbose_name_plural': 'Misiones de picking',
                'ordering': ['-created_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PICKED', 'Recogida'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recogida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('kit_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='wms.assemblykitline', verbose_name='Linea de kit')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='wms.materiallot', verbose_name='Lote')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='wms.material', verbose_name='Material')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='wms.pickmission', verbose_name='Mision')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='wms.materialserial', verbose_name='Serie')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea de picking',
                'verbose_name_plural': 'Tareas de picking',
                'ordering': ['mission', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('minimum_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Minimo')),
                ('maximum_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Maximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_destinations', to='core.location', verbose_name='Ubicacion a reponer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_rules', to='wms.material', verbose_name='Material')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_sources', to='core.location', verbose_name='Ubicacion origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla de reposicion',
                'verbose_name_plural': 'Reglas de reposicion',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='KanbanSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('requested_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad solicitada')),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('FULFILLED', 'Atendida'), ('CANCELLED', 'Cancelada')], db_index=True, default='OPEN', max_length=20, verbose_name='Estado')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name='Motivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('pick_mission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_signal', to='wms.pickmission', verbose_name='Mision de picking')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='wms.replenishmentrule', verbose_name='Regla')),
            ],
            options={
                'verbose_name': 'Senal Kanban',
                'verbose_name_plural': 'Senales Kanban',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assemblykitline',
            constraint=models.UniqueConstraint(fields=('kit', 'material'), name='wms_kit_line_material_uq'),
        ),
    ]
