# Generated by Django 5.2.17 on 2026-08-26 11:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0010_plant_plantarea_productionmeasurement_and_more'),
        ('core', '0001_initial'),
        ('wms', '0002_line_feeding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Recepcion'), ('TRANSFER', 'Traslado'), ('STATUS_CHANGE', 'Cambio de estado'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('ADJUSTMENT_OUT', 'Ajuste negativo'), ('CONSUMPTION', 'Consumo de ensamble')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='AssemblyMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=120, unique=True, verbose_name='Codigo de evento')),
                ('consumed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/hora de consumo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Datos de integracion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('installed_component', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wms_consumption', to='assembly.installedcomponent', verbose_name='Componente instalado')),
                ('inventory_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_consumption', to='wms.inventorymovement', verbose_name='Movimiento de inventario')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_consumptions', to='wms.materiallot', verbose_name='Lote')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_consumptions', to='wms.material', verbose_name='Material')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_consumptions', to='wms.materialserial', verbose_name='Serie')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_consumptions', to='core.location', verbose_name='Ubicacion de consumo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumo de material de ensamble',
                'verbose_name_plural': 'Consumos de material de ensamble',
                'ordering': ['-consumed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PokaYokeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_reference', models.CharField(max_length=120, unique=True, verbose_name='Referencia de escaneo')),
                ('scanned_material_code', models.CharField(max_length=80, verbose_name='Material escaneado')),
                ('scanned_lot_number', models.CharField(blank=True, max_length=120, verbose_name='Lote escaneado')),
                ('scanned_serial_number', models.CharField(blank=True, max_length=120, verbose_name='Serie escaneada')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14, verbose_name='Cantidad')),
                ('result', models.CharField(choices=[('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], db_index=True, max_length=20, verbose_name='Resultado')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name='Motivo')),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/hora de intento')),
                ('consumption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_attempt', to='wms.assemblymaterialconsumption', verbose_name='Consumo generado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_attempts', to='assembly.routestepcomponentrequirement', verbose_name='Requerimiento')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poka_yoke_attempts', to='assembly.assemblystation', verbose_name='Estacion')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poka_yoke_attempts', to='assembly.serializedunit', verbose_name='Unidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de poka-yoke',
                'verbose_name_plural': 'Intentos de poka-yoke',
                'ordering': ['-attempted_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='assemblymaterialconsumption',
            index=models.Index(fields=['material', 'consumed_at'], name='wms_consume_material_time_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblymaterialconsumption',
            index=models.Index(fields=['source_location', 'consumed_at'], name='wms_consume_location_time_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokeattempt',
            index=models.Index(fields=['result', 'attempted_at'], name='wms_poka_result_time_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokeattempt',
            index=models.Index(fields=['unit', 'attempted_at'], name='wms_poka_unit_time_idx'),
        ),
    ]
