from django.urls import path

from .views import (
    AdvancedMESDashboardView,
    AndonSignalControlView,
    AndonSignalCreateView,
    AndonSignalListView,
    AndonSignalUpdateView,
    PlantAreaCreateView,
    PlantAreaListView,
    PlantAreaUpdateView,
    PlantCreateView,
    PlantListView,
    PlantUpdateView,
    AssemblyLineCreateView,
    AssemblyLineListView,
    AssemblyLineUpdateView,
    AssemblyRouteCreateView,
    AssemblyRouteListView,
    AssemblyRouteStepCreateView,
    AssemblyRouteStepListView,
    AssemblyRouteStepUpdateView,
    AssemblyRouteUpdateView,
    AssemblyStationCreateView,
    AssemblyStationListView,
    AssemblyStationUpdateView,
    ExternalMaterialKitCreateView,
    ExternalMaterialKitListView,
    ExternalMaterialKitUpdateView,
    EquipmentCreateView,
    EquipmentListView,
    EquipmentUpdateView,
    InstalledComponentCreateView,
    InstalledComponentListView,
    InstalledComponentUpdateView,
    GenealogySearchView,
    LineBalanceStudyCreateView,
    LineBalanceStudyDetailView,
    LineBalanceStudyListView,
    LineBalanceStudyUpdateView,
    ModelMixPlanCreateView,
    ModelMixPlanDetailView,
    ModelMixPlanItemCreateView,
    ModelMixPlanItemUpdateView,
    ModelMixPlanListView,
    ModelMixPlanUpdateView,
    ProductCreateView,
    ProductListView,
    ProductUpdateView,
    ProductVersionCreateView,
    ProductVersionListView,
    ProductVersionUpdateView,
    ProductionMeasurementCreateView,
    ProductionMeasurementListView,
    ProductionMeasurementUpdateView,
    ProductionDowntimeControlView,
    ProductionDowntimeCreateView,
    ProductionDowntimeListView,
    ProductionDowntimeUpdateView,
    ProductionDashboardView,
    ProductionDashboardStatusView,
    ProductionMetricsView,
    ProductionPlanControlView,
    ProductionPlanCreateView,
    ProductionPlanListView,
    ProductionPlanUpdateView,
    ProductionOrderCreateView,
    ProductionOrderDetailView,
    ProductionOrderListView,
    ProductionOrderUpdateView,
    ProductionQueueControlView,
    ProductionQueueItemCreateView,
    ProductionQueueItemUpdateView,
    ProductionQueueListView,
    QualityGateCreateView,
    QualityGateListView,
    QualityGateReviewView,
    QualityGateUpdateView,
    ReleaseApprovalCreateView,
    ReleaseApprovalListView,
    ReleaseApprovalUpdateView,
    ReworkOrderCreateView,
    ReworkOrderControlView,
    ReworkOrderListView,
    ReworkOrderUpdateView,
    RouteStepComponentRequirementCreateView,
    RouteStepComponentRequirementListView,
    RouteStepComponentRequirementUpdateView,
    RouteStepParameterCreateView,
    RouteStepParameterListView,
    RouteStepParameterUpdateView,
    SerializedUnitCreateView,
    SerializedUnitDetailView,
    SerializedUnitListView,
    SerializedUnitUpdateView,
    StationOfflineEventControlView,
    StationOfflineEventCreateView,
    StationOfflineEventListView,
    StationQueueView,
    StationConsoleView,
    UnitStationEventCreateView,
    UnitStationEventListView,
    UnitStationEventUpdateView,
)


app_name = "assembly"

urlpatterns = [
    path("", ProductionDashboardView.as_view(), name="index"),
    path("panel/estado/", ProductionDashboardStatusView.as_view(), name="dashboard_status"),
    path("indicadores/", ProductionMetricsView.as_view(), name="metrics"),
    path("estacion/", StationConsoleView.as_view(), name="station_console"),
    path("unidades/", SerializedUnitListView.as_view(), name="unit_list"),
    path("unidades/nueva/", SerializedUnitCreateView.as_view(), name="unit_create"),
    path("unidades/<int:pk>/", SerializedUnitDetailView.as_view(), name="unit_detail"),
    path("unidades/<int:pk>/editar/", SerializedUnitUpdateView.as_view(), name="unit_update"),
    path("ordenes/", ProductionOrderListView.as_view(), name="order_list"),
    path("ordenes/nueva/", ProductionOrderCreateView.as_view(), name="order_create"),
    path("ordenes/<int:pk>/", ProductionOrderDetailView.as_view(), name="order_detail"),
    path("ordenes/<int:pk>/editar/", ProductionOrderUpdateView.as_view(), name="order_update"),
    path("planes/", ProductionPlanListView.as_view(), name="plan_list"),
    path("planes/nuevo/", ProductionPlanCreateView.as_view(), name="plan_create"),
    path("planes/<int:pk>/gestionar/", ProductionPlanControlView.as_view(), name="plan_control"),
    path("planes/<int:pk>/editar/", ProductionPlanUpdateView.as_view(), name="plan_update"),
    path("secuencia/", ProductionQueueListView.as_view(), name="queue_list"),
    path("secuencia/nueva/", ProductionQueueItemCreateView.as_view(), name="queue_create"),
    path("secuencia/estaciones/", StationQueueView.as_view(), name="station_queue"),
    path("secuencia/<int:pk>/gestionar/", ProductionQueueControlView.as_view(), name="queue_control"),
    path("secuencia/<int:pk>/editar/", ProductionQueueItemUpdateView.as_view(), name="queue_update"),
    path("balanceo/", LineBalanceStudyListView.as_view(), name="balance_list"),
    path("balanceo/nuevo/", LineBalanceStudyCreateView.as_view(), name="balance_create"),
    path("balanceo/<int:pk>/", LineBalanceStudyDetailView.as_view(), name="balance_detail"),
    path("balanceo/<int:pk>/editar/", LineBalanceStudyUpdateView.as_view(), name="balance_update"),
    path("avanzado/", AdvancedMESDashboardView.as_view(), name="advanced"),
    path("andon/", AndonSignalListView.as_view(), name="andon_list"),
    path("andon/nueva/", AndonSignalCreateView.as_view(), name="andon_create"),
    path("andon/<int:pk>/gestionar/", AndonSignalControlView.as_view(), name="andon_control"),
    path("andon/<int:pk>/editar/", AndonSignalUpdateView.as_view(), name="andon_update"),
    path("paros/", ProductionDowntimeListView.as_view(), name="downtime_list"),
    path("paros/nuevo/", ProductionDowntimeCreateView.as_view(), name="downtime_create"),
    path("paros/<int:pk>/gestionar/", ProductionDowntimeControlView.as_view(), name="downtime_control"),
    path("paros/<int:pk>/editar/", ProductionDowntimeUpdateView.as_view(), name="downtime_update"),
    path("offline/", StationOfflineEventListView.as_view(), name="offline_list"),
    path("offline/nuevo/", StationOfflineEventCreateView.as_view(), name="offline_create"),
    path("offline/<int:pk>/gestionar/", StationOfflineEventControlView.as_view(), name="offline_control"),
    path("mix/", ModelMixPlanListView.as_view(), name="mix_list"),
    path("mix/nuevo/", ModelMixPlanCreateView.as_view(), name="mix_create"),
    path("mix/<int:pk>/", ModelMixPlanDetailView.as_view(), name="mix_detail"),
    path("mix/<int:pk>/editar/", ModelMixPlanUpdateView.as_view(), name="mix_update"),
    path("mix-items/nuevo/", ModelMixPlanItemCreateView.as_view(), name="mix_item_create"),
    path("mix-items/<int:pk>/editar/", ModelMixPlanItemUpdateView.as_view(), name="mix_item_update"),
    path("kits/", ExternalMaterialKitListView.as_view(), name="kit_list"),
    path("kits/nuevo/", ExternalMaterialKitCreateView.as_view(), name="kit_create"),
    path("kits/<int:pk>/editar/", ExternalMaterialKitUpdateView.as_view(), name="kit_update"),
    path("productos/", ProductListView.as_view(), name="product_list"),
    path("productos/nuevo/", ProductCreateView.as_view(), name="product_create"),
    path("productos/<int:pk>/editar/", ProductUpdateView.as_view(), name="product_update"),
    path("versiones/", ProductVersionListView.as_view(), name="version_list"),
    path("versiones/nueva/", ProductVersionCreateView.as_view(), name="version_create"),
    path("versiones/<int:pk>/editar/", ProductVersionUpdateView.as_view(), name="version_update"),
    path("plantas/", PlantListView.as_view(), name="plant_list"),
    path("plantas/nueva/", PlantCreateView.as_view(), name="plant_create"),
    path("plantas/<int:pk>/editar/", PlantUpdateView.as_view(), name="plant_update"),
    path("areas/", PlantAreaListView.as_view(), name="area_list"),
    path("areas/nueva/", PlantAreaCreateView.as_view(), name="area_create"),
    path("areas/<int:pk>/editar/", PlantAreaUpdateView.as_view(), name="area_update"),
    path("lineas/", AssemblyLineListView.as_view(), name="line_list"),
    path("lineas/nueva/", AssemblyLineCreateView.as_view(), name="line_create"),
    path("lineas/<int:pk>/editar/", AssemblyLineUpdateView.as_view(), name="line_update"),
    path("estaciones/", AssemblyStationListView.as_view(), name="station_list"),
    path("estaciones/nueva/", AssemblyStationCreateView.as_view(), name="station_create"),
    path("estaciones/<int:pk>/editar/", AssemblyStationUpdateView.as_view(), name="station_update"),
    path("rutas/", AssemblyRouteListView.as_view(), name="route_list"),
    path("rutas/nueva/", AssemblyRouteCreateView.as_view(), name="route_create"),
    path("rutas/<int:pk>/editar/", AssemblyRouteUpdateView.as_view(), name="route_update"),
    path("pasos/", AssemblyRouteStepListView.as_view(), name="step_list"),
    path("pasos/nuevo/", AssemblyRouteStepCreateView.as_view(), name="step_create"),
    path("pasos/<int:pk>/editar/", AssemblyRouteStepUpdateView.as_view(), name="step_update"),
    path("parametros/", RouteStepParameterListView.as_view(), name="parameter_list"),
    path("parametros/nuevo/", RouteStepParameterCreateView.as_view(), name="parameter_create"),
    path("parametros/<int:pk>/editar/", RouteStepParameterUpdateView.as_view(), name="parameter_update"),
    path("requerimientos/", RouteStepComponentRequirementListView.as_view(), name="requirement_list"),
    path("requerimientos/nuevo/", RouteStepComponentRequirementCreateView.as_view(), name="requirement_create"),
    path("requerimientos/<int:pk>/editar/", RouteStepComponentRequirementUpdateView.as_view(), name="requirement_update"),
    path("eventos/", UnitStationEventListView.as_view(), name="event_list"),
    path("eventos/nuevo/", UnitStationEventCreateView.as_view(), name="event_create"),
    path("eventos/<int:pk>/editar/", UnitStationEventUpdateView.as_view(), name="event_update"),
    path("mediciones/", ProductionMeasurementListView.as_view(), name="measurement_list"),
    path("mediciones/nueva/", ProductionMeasurementCreateView.as_view(), name="measurement_create"),
    path("mediciones/<int:pk>/editar/", ProductionMeasurementUpdateView.as_view(), name="measurement_update"),
    path("genealogia/", GenealogySearchView.as_view(), name="genealogy"),
    path("componentes/", InstalledComponentListView.as_view(), name="component_list"),
    path("componentes/nuevo/", InstalledComponentCreateView.as_view(), name="component_create"),
    path("componentes/<int:pk>/editar/", InstalledComponentUpdateView.as_view(), name="component_update"),
    path("calidad/", QualityGateListView.as_view(), name="quality_list"),
    path("calidad/nuevo/", QualityGateCreateView.as_view(), name="quality_create"),
    path("calidad/<int:pk>/revisar/", QualityGateReviewView.as_view(), name="quality_review"),
    path("calidad/<int:pk>/editar/", QualityGateUpdateView.as_view(), name="quality_update"),
    path("retrabajos/", ReworkOrderListView.as_view(), name="rework_list"),
    path("retrabajos/nuevo/", ReworkOrderCreateView.as_view(), name="rework_create"),
    path("retrabajos/<int:pk>/gestionar/", ReworkOrderControlView.as_view(), name="rework_control"),
    path("retrabajos/<int:pk>/editar/", ReworkOrderUpdateView.as_view(), name="rework_update"),
    path("liberacion/", ReleaseApprovalListView.as_view(), name="release_list"),
    path("liberacion/nueva/", ReleaseApprovalCreateView.as_view(), name="release_create"),
    path("liberacion/<int:pk>/editar/", ReleaseApprovalUpdateView.as_view(), name="release_update"),
    path("equipos/", EquipmentListView.as_view(), name="equipment_list"),
    path("equipos/nuevo/", EquipmentCreateView.as_view(), name="equipment_create"),
    path("equipos/<int:pk>/editar/", EquipmentUpdateView.as_view(), name="equipment_update"),
]
