from django.urls import path

from . import views


urlpatterns = [
    path("", views.WMSDashboardView.as_view(), name="dashboard"),
    path("materiales/", views.MaterialListView.as_view(), name="material_list"),
    path("materiales/nuevo/", views.MaterialCreateView.as_view(), name="material_create"),
    path("materiales/<int:pk>/editar/", views.MaterialUpdateView.as_view(), name="material_update"),
    path("categorias/", views.MaterialCategoryListView.as_view(), name="category_list"),
    path("categorias/nueva/", views.MaterialCategoryCreateView.as_view(), name="category_create"),
    path("categorias/<int:pk>/editar/", views.MaterialCategoryUpdateView.as_view(), name="category_update"),
    path("ubicaciones/", views.LocationProfileListView.as_view(), name="location_profile_list"),
    path("ubicaciones/nueva/", views.LocationProfileCreateView.as_view(), name="location_profile_create"),
    path("ubicaciones/<int:pk>/editar/", views.LocationProfileUpdateView.as_view(), name="location_profile_update"),
    path("recepciones/", views.InboundReceiptListView.as_view(), name="receipt_list"),
    path("recepciones/nueva/", views.InboundReceiptCreateView.as_view(), name="receipt_create"),
    path("recepciones/<int:pk>/", views.InboundReceiptDetailView.as_view(), name="receipt_detail"),
    path("recepciones/<int:pk>/editar/", views.InboundReceiptUpdateView.as_view(), name="receipt_update"),
    path("recepciones/<int:receipt_pk>/lineas/nueva/", views.InboundReceiptLineCreateView.as_view(), name="receipt_line_create"),
    path("recepciones/lineas/<int:pk>/recibir/", views.ReceiveReceiptLineView.as_view(), name="receipt_line_receive"),
    path("inventario/", views.InventoryBalanceListView.as_view(), name="balance_list"),
    path("movimientos/", views.InventoryMovementListView.as_view(), name="movement_list"),
    path("movimientos/nuevo/", views.InventoryOperationCreateView.as_view(), name="movement_create"),
    path("linea/instalar/", views.LineInstallationView.as_view(), name="line_install"),
    path("consumos/", views.AssemblyMaterialConsumptionListView.as_view(), name="consumption_list"),
    path("kits/", views.AssemblyKitListView.as_view(), name="kit_list"),
    path("kits/nuevo/", views.AssemblyKitCreateView.as_view(), name="kit_create"),
    path("kits/<int:pk>/", views.AssemblyKitDetailView.as_view(), name="kit_detail"),
    path("kits/<int:pk>/editar/", views.AssemblyKitUpdateView.as_view(), name="kit_update"),
    path("kits/<int:kit_pk>/lineas/nueva/", views.AssemblyKitLineCreateView.as_view(), name="kit_line_create"),
    path("kits/<int:pk>/<str:action>/", views.KitActionView.as_view(), name="kit_action"),
    path("picking/", views.PickMissionListView.as_view(), name="pick_mission_list"),
    path("picking/nueva/", views.PickMissionCreateView.as_view(), name="pick_mission_create"),
    path("picking/<int:pk>/", views.PickMissionDetailView.as_view(), name="pick_mission_detail"),
    path("picking/<int:mission_pk>/tareas/nueva/", views.PickTaskCreateView.as_view(), name="pick_task_create"),
    path("picking/<int:pk>/<str:action>/", views.PickMissionActionView.as_view(), name="pick_mission_action"),
    path("picking/<int:pk>/tareas/<int:task_pk>/<str:action>/", views.PickMissionActionView.as_view(), name="pick_task_action"),
    path("kanban/", views.KanbanSignalListView.as_view(), name="kanban_signal_list"),
    path("kanban/nueva/", views.KanbanSignalCreateView.as_view(), name="kanban_signal_create"),
    path("kanban/reglas/", views.ReplenishmentRuleListView.as_view(), name="replenishment_rule_list"),
    path("kanban/reglas/nueva/", views.ReplenishmentRuleCreateView.as_view(), name="replenishment_rule_create"),
    path("kanban/reglas/<int:pk>/editar/", views.ReplenishmentRuleUpdateView.as_view(), name="replenishment_rule_update"),
    path("kanban/<int:pk>/", views.KanbanSignalDetailView.as_view(), name="kanban_signal_detail"),
    path("kanban/<int:pk>/<str:action>/", views.KanbanSignalActionView.as_view(), name="kanban_signal_action"),
]
