# Generated by Django 5.2.17 on 2026-08-24 21:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_alter_serializedunit_status_assemblyline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStepComponentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_code', models.CharField(max_length=80, verbose_name='Codigo de parte')),
                ('part_name', models.CharField(blank=True, max_length=180, verbose_name='Nombre de parte')),
                ('quantity_required', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, verbose_name='Cantidad requerida')),
                ('traceability', models.CharField(choices=[('SERIAL', 'Serial obligatorio'), ('LOT', 'Lote obligatorio'), ('SERIAL_OR_LOT', 'Serial o lote'), ('SERIAL_AND_LOT', 'Serial y lote')], default='SERIAL_OR_LOT', max_length=20, verbose_name='Trazabilidad requerida')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Critico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('route_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_requirements', to='assembly.assemblyroutestep', verbose_name='Paso de ruta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente requerido por paso',
                'verbose_name_plural': 'Componentes requeridos por paso',
                'ordering': ['route_step__route__code', 'route_step__sequence', 'part_code'],
            },
        ),
        migrations.AddField(
            model_name='installedcomponent',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_components', to='assembly.routestepcomponentrequirement', verbose_name='Requerimiento'),
        ),
        migrations.AddIndex(
            model_name='routestepcomponentrequirement',
            index=models.Index(fields=['part_code'], name='asem_req_part_code_idx'),
        ),
        migrations.AddIndex(
            model_name='routestepcomponentrequirement',
            index=models.Index(fields=['is_active'], name='asem_req_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestepcomponentrequirement',
            constraint=models.UniqueConstraint(fields=('route_step', 'part_code'), name='asem_req_step_part_uq'),
        ),
    ]
