# Generated by Django 5.2.17 on 2026-08-24 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_routestepcomponentrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkorder',
            name='closure_evidence_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Evidencia de cierre'),
        ),
        migrations.AddField(
            model_name='reworkorder',
            name='reinspection_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_reinspections', to='assembly.qualitygate', verbose_name='Control de reinspeccion'),
        ),
    ]
