# Generated by Django 5.2.17 on 2026-08-24 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_reworkorder_closure_evidence_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('planned_date', models.DateField(db_index=True, verbose_name='Fecha planificada')),
                ('shift', models.CharField(max_length=40, verbose_name='Turno')),
                ('target_quantity', models.PositiveIntegerField(verbose_name='Cantidad objetivo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RELEASED', 'Liberado'), ('IN_EXECUTION', 'En ejecucion'), ('CLOSED', 'Cerrado'), ('CANCELLED', 'Cancelado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], db_index=True, default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('planned_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio planificado')),
                ('planned_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin planificado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='assembly.assemblyline', verbose_name='Linea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='assembly.productversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Plan de produccion',
                'verbose_name_plural': 'Planes de produccion',
                'ordering': ['planned_date', 'priority', 'code'],
            },
        ),
        migrations.AddField(
            model_name='serializedunit',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='assembly.productionplan', verbose_name='Plan de produccion'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['status', 'planned_date'], name='prod_plan_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['line', 'planned_date'], name='prod_plan_line_date_idx'),
        ),
    ]
