# Generated by Django 5.2.17 on 2026-08-24 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_productionplan_serializedunit_production_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(verbose_name='Secuencia')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], db_index=True, default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('QUEUED', 'En cola'), ('READY', 'Lista'), ('IN_PROGRESS', 'En proceso'), ('HOLD', 'Retenida'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], db_index=True, default='QUEUED', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_items', to='assembly.assemblyline', verbose_name='Linea')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='assembly.productionplan', verbose_name='Plan de produccion')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_items', to='assembly.assemblyroute', verbose_name='Ruta')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='assembly.serializedunit', verbose_name='Unidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de secuencia',
                'verbose_name_plural': 'Items de secuencia',
                'ordering': ['line__code', 'sequence', 'id'],
                'indexes': [models.Index(fields=['line', 'sequence'], name='prod_queue_line_seq_idx'), models.Index(fields=['status', 'priority'], name='prod_queue_status_pri_idx')],
            },
        ),
    ]
