# Generated by Django 5.2.17 on 2026-08-25 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0006_productionqueueitem'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=120, unique=True, verbose_name='Identificador externo')),
                ('equipment_code', models.CharField(max_length=50, verbose_name='Codigo de equipo recibido')),
                ('station_code', models.CharField(blank=True, max_length=50, verbose_name='Codigo de estacion recibido')),
                ('unit_serial_number', models.CharField(max_length=120, verbose_name='Serie de unidad recibida')),
                ('operator_username', models.CharField(max_length=150, verbose_name='Operario recibido')),
                ('event_type', models.CharField(choices=[('ARRIVED', 'Ingreso a estacion'), ('STARTED', 'Inicio'), ('PAUSED', 'Pausa'), ('RESUMED', 'Reinicio'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallo'), ('REWORK_OUT', 'Salida a retrabajo'), ('REWORK_IN', 'Reingreso de retrabajo')], max_length=20, verbose_name='Tipo de evento')),
                ('event_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/hora informada')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de recepcion')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Carga original')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSED', 'Procesado'), ('REJECTED', 'Rechazado')], db_index=True, default='RECEIVED', max_length=20, verbose_name='Estado de procesamiento')),
                ('result_detail', models.TextField(blank=True, verbose_name='Detalle de resultado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de procesamiento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_assembly_events', to='core.equipmentintegration', verbose_name='Equipo resuelto')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_assembly_events', to=settings.AUTH_USER_MODEL, verbose_name='Operario resuelto')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_equipment_events', to='assembly.assemblystation', verbose_name='Estacion resuelta')),
                ('station_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_equipment_event', to='assembly.unitstationevent', verbose_name='Evento de estacion creado')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_equipment_events', to='assembly.serializedunit', verbose_name='Unidad resuelta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento recibido de equipo',
                'verbose_name_plural': 'Eventos recibidos de equipos',
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='equip_inbound_status_time_idx'), models.Index(fields=['equipment_code', 'event_at'], name='equip_inbound_code_time_idx')],
            },
        ),
    ]
