# Generated by Django 5.2.17 on 2026-08-25 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_equipmentinboundevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineBalanceStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('planned_units', models.PositiveIntegerField(default=1, verbose_name='Unidades planificadas')),
                ('shift_duration_seconds', models.PositiveIntegerField(default=28800, verbose_name='Duracion de turno (segundos)')),
                ('target_takt_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Takt objetivo (segundos)')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Datos reales desde')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Datos reales hasta')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CALCULATED', 'Calculado'), ('APPROVED', 'Aprobado'), ('ARCHIVED', 'Archivado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de calculo')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Resultado calculado')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Recomendaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_studies', to='assembly.assemblyline', verbose_name='Linea')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_studies', to='assembly.productionplan', verbose_name='Plan de produccion')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_studies', to='assembly.assemblyroute', verbose_name='Ruta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_studies', to='assembly.productversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Estudio de balanceo',
                'verbose_name_plural': 'Estudios de balanceo',
                'ordering': ['-generated_at', '-created_at', 'code'],
                'indexes': [models.Index(fields=['line', 'status'], name='line_balance_line_status_idx'), models.Index(fields=['version', 'status'], name='line_balance_ver_status_idx')],
            },
        ),
    ]
