# Generated by Django 5.2.17 on 2026-08-25 15:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0008_linebalancestudy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitstationevent',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('API', 'API'), ('EQUIPMENT', 'Equipo'), ('OFFLINE', 'Offline')], default='MANUAL', max_length=20, verbose_name='Origen'),
        ),
        migrations.CreateModel(
            name='AndonSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('severity', models.CharField(choices=[('INFO', 'Informativa'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Critica')], db_index=True, default='WARNING', max_length=20, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('ACKNOWLEDGED', 'Reconocida'), ('RESOLVED', 'Resuelta'), ('CANCELLED', 'Cancelada')], db_index=True, default='OPEN', max_length=20, verbose_name='Estado')),
                ('title', models.CharField(max_length=160, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('API', 'API'), ('EQUIPMENT', 'Equipo'), ('OFFLINE', 'Offline')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/hora apertura')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora reconocimiento')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora resolucion')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolucion')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_signals_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='Reconocida por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='andon_signals', to='assembly.assemblyline', verbose_name='Linea')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_signals_opened', to=settings.AUTH_USER_MODEL, verbose_name='Abierta por')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_signals', to='assembly.productionplan', verbose_name='Plan de produccion')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_signals_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='andon_signals', to='assembly.assemblystation', verbose_name='Estacion')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_signals', to='assembly.serializedunit', verbose_name='Unidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Senal Andon',
                'verbose_name_plural': 'Senales Andon',
                'ordering': ['status', '-severity', '-opened_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMaterialKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('external_system', models.CharField(default='B22', max_length=50, verbose_name='Sistema externo')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia externa')),
                ('container_code', models.CharField(blank=True, max_length=120, verbose_name='Contenedor')),
                ('lot_number', models.CharField(blank=True, max_length=120, verbose_name='Lote')),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, verbose_name='Cantidad esperada')),
                ('received_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Cantidad recibida')),
                ('status', models.CharField(choices=[('PLANNED', 'Planificado'), ('RECEIVED', 'Recibido'), ('CONSUMED', 'Consumido'), ('HOLD', 'Retenido'), ('CANCELLED', 'Cancelado')], db_index=True, default='PLANNED', max_length=20, verbose_name='Estado')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora recepcion')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_material_kits', to='assembly.assemblyline', verbose_name='Linea')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_material_kits', to='assembly.productionplan', verbose_name='Plan de produccion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_material_kits', to='assembly.productversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Kit externo de material',
                'verbose_name_plural': 'Kits externos de material',
                'ordering': ['status', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ModelMixPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('planned_date', models.DateField(db_index=True, verbose_name='Fecha planificada')),
                ('shift', models.CharField(max_length=40, verbose_name='Turno')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('CLOSED', 'Cerrado'), ('CANCELLED', 'Cancelado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_mix_plans', to='assembly.assemblyline', verbose_name='Linea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de mix de modelos',
                'verbose_name_plural': 'Planes de mix de modelos',
                'ordering': ['planned_date', 'line__code', 'shift', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ModelMixPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_quantity', models.PositiveIntegerField(verbose_name='Cantidad planificada')),
                ('sequence_bias', models.PositiveSmallIntegerField(default=1, verbose_name='Peso de secuencia')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], db_index=True, default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('mix_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assembly.modelmixplan', verbose_name='Mix de modelos')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_mix_items', to='assembly.productionplan', verbose_name='Plan generado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_mix_items', to='assembly.productversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Item de mix de modelos',
                'verbose_name_plural': 'Items de mix de modelos',
                'ordering': ['mix_plan', 'sequence_bias', 'version__product__code', 'version__code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado'), ('CANCELLED', 'Cancelado')], db_index=True, default='OPEN', max_length=20, verbose_name='Estado')),
                ('cause_category', models.CharField(choices=[('EQUIPMENT', 'Equipo'), ('MATERIAL', 'Material'), ('QUALITY', 'Calidad'), ('CHANGEOVER', 'Cambio de modelo'), ('STAFFING', 'Personal'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Otro')], db_index=True, default='OTHER', max_length=20, verbose_name='Categoria')),
                ('cause_code', models.CharField(max_length=80, verbose_name='Codigo de causa')),
                ('cause_description', models.TextField(blank=True, verbose_name='Descripcion de causa')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Inicio')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('evidence_reference', models.CharField(blank=True, max_length=120, verbose_name='Evidencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('andon_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='assembly.andonsignal', verbose_name='Senal Andon')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes_closed', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='assembly.assemblyline', verbose_name='Linea')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes_opened', to=settings.AUTH_USER_MODEL, verbose_name='Abierto por')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='assembly.productionplan', verbose_name='Plan de produccion')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='assembly.assemblystation', verbose_name='Estacion')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='assembly.serializedunit', verbose_name='Unidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paro de produccion',
                'verbose_name_plural': 'Paros de produccion',
                'ordering': ['status', '-started_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StationOfflineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=120, unique=True, verbose_name='Identificador externo')),
                ('unit_serial_number', models.CharField(max_length=120, verbose_name='Serial de unidad')),
                ('operator_username', models.CharField(blank=True, max_length=150, verbose_name='Operario')),
                ('event_type', models.CharField(choices=[('ARRIVED', 'Ingreso a estacion'), ('STARTED', 'Inicio'), ('PAUSED', 'Pausa'), ('RESUMED', 'Reinicio'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallo'), ('REWORK_OUT', 'Salida a retrabajo'), ('REWORK_IN', 'Reingreso de retrabajo')], max_length=20, verbose_name='Tipo de evento')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Capturado en terminal')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload local')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SYNCED', 'Sincronizado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('result_detail', models.TextField(blank=True, verbose_name='Resultado')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_events', to='assembly.assemblystation', verbose_name='Estacion')),
                ('station_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_source', to='assembly.unitstationevent', verbose_name='Evento sincronizado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento offline de estacion',
                'verbose_name_plural': 'Eventos offline de estacion',
                'ordering': ['status', 'captured_at', 'external_id'],
            },
        ),
        migrations.AddIndex(
            model_name='andonsignal',
            index=models.Index(fields=['line', 'status'], name='andon_line_status_idx'),
        ),
        migrations.AddIndex(
            model_name='andonsignal',
            index=models.Index(fields=['station', 'status'], name='andon_station_status_idx'),
        ),
        migrations.AddIndex(
            model_name='andonsignal',
            index=models.Index(fields=['severity', 'opened_at'], name='andon_severity_time_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmaterialkit',
            index=models.Index(fields=['status', 'external_system'], name='ext_kit_status_system_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmaterialkit',
            index=models.Index(fields=['version', 'status'], name='ext_kit_version_status_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmixplan',
            index=models.Index(fields=['line', 'planned_date'], name='mix_plan_line_date_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmixplan',
            index=models.Index(fields=['status', 'planned_date'], name='mix_plan_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelmixplanitem',
            constraint=models.UniqueConstraint(fields=('mix_plan', 'version'), name='mix_item_plan_version_uq'),
        ),
        migrations.AddIndex(
            model_name='productiondowntime',
            index=models.Index(fields=['line', 'status'], name='downtime_line_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondowntime',
            index=models.Index(fields=['station', 'status'], name='downtime_station_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondowntime',
            index=models.Index(fields=['cause_category', 'started_at'], name='downtime_cause_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stationofflineevent',
            index=models.Index(fields=['station', 'status'], name='offline_station_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stationofflineevent',
            index=models.Index(fields=['status', 'captured_at'], name='offline_status_time_idx'),
        ),
    ]
