# Generated by Django 5.2.17 on 2026-08-25 21:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0009_alter_unitstationevent_source_andonsignal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Direccion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlantArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Area de planta',
                'verbose_name_plural': 'Areas de planta',
                'ordering': ['plant__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valor numerico')),
                ('text_value', models.CharField(blank=True, max_length=180, verbose_name='Valor texto')),
                ('unit_label', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Minimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Maximo')),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('PASS', 'Aprobado'), ('FAIL', 'Fuera de rango'), ('NOT_APPLICABLE', 'No aplica')], db_index=True, default='PENDING', max_length=20, verbose_name='Resultado')),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('PLC', 'PLC'), ('MACHINE', 'Maquina'), ('API', 'API'), ('OPC_UA', 'OPC UA'), ('MQTT', 'MQTT'), ('SENSOR', 'Sensor')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('measured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/hora medicion')),
                ('evidence_reference', models.CharField(blank=True, max_length=120, verbose_name='Evidencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Medicion productiva',
                'verbose_name_plural': 'Mediciones productivas',
                'ordering': ['-measured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='OP')),
                ('target_quantity', models.PositiveIntegerField(verbose_name='Cantidad objetivo')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha requerida')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RELEASED', 'Liberada'), ('IN_EXECUTION', 'En ejecucion'), ('COMPLETED', 'Completada'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], db_index=True, default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia externa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Orden de produccion',
                'verbose_name_plural': 'Ordenes de produccion',
                'ordering': ['due_date', 'priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RouteStepParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('parameter_type', models.CharField(choices=[('NUMERIC', 'Numerico'), ('TEXT', 'Texto'), ('BOOLEAN', 'Si/No'), ('CHOICE', 'Lista')], default='NUMERIC', max_length=20, verbose_name='Tipo')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('target_value', models.CharField(blank=True, max_length=80, verbose_name='Valor objetivo')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Minimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Maximo')),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('PLC', 'PLC'), ('MACHINE', 'Maquina'), ('API', 'API'), ('OPC_UA', 'OPC UA'), ('MQTT', 'MQTT'), ('SENSOR', 'Sensor')], default='MANUAL', max_length=20, verbose_name='Origen esperado')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('is_quality_critical', models.BooleanField(default=False, verbose_name='Critico para calidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Parametro productivo',
                'verbose_name_plural': 'Parametros productivos',
                'ordering': ['route_step__route__code', 'route_step__sequence', 'code'],
            },
        ),
        migrations.AddField(
            model_name='assemblyroutestep',
            name='acceptance_criteria',
            field=models.TextField(blank=True, verbose_name='Criterios de aceptacion'),
        ),
        migrations.AddField(
            model_name='assemblyroutestep',
            name='media_reference',
            field=models.CharField(blank=True, max_length=180, verbose_name='Referencia visual/documento'),
        ),
        migrations.AddField(
            model_name='assemblyroutestep',
            name='safety_notes',
            field=models.TextField(blank=True, verbose_name='Notas de seguridad'),
        ),
        migrations.AddField(
            model_name='qualitygate',
            name='defect_classification',
            field=models.CharField(choices=[('PROCESS', 'Proceso'), ('MATERIAL', 'Material'), ('EQUIPMENT', 'Equipo'), ('DOCUMENTATION', 'Documentacion'), ('SAFETY', 'Seguridad'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Clasificacion'),
        ),
        migrations.AddField(
            model_name='qualitygate',
            name='defect_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Codigo de defecto'),
        ),
        migrations.AddField(
            model_name='qualitygate',
            name='defect_severity',
            field=models.CharField(choices=[('MINOR', 'Menor'), ('MAJOR', 'Mayor'), ('CRITICAL', 'Critica')], default='MINOR', max_length=20, verbose_name='Severidad'),
        ),
        migrations.AddField(
            model_name='qualitygate',
            name='responsible_area',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsable/area'),
        ),
        migrations.AddField(
            model_name='qualitygate',
            name='root_cause',
            field=models.CharField(blank=True, max_length=180, verbose_name='Causa raiz'),
        ),
        migrations.AddIndex(
            model_name='qualitygate',
            index=models.Index(fields=['defect_code'], name='qgate_defect_code_idx'),
        ),
        migrations.AddField(
            model_name='plant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantarea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantarea',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='assembly.plant', verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='plantarea',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assemblyline',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='assembly.plantarea', verbose_name='Area de planta'),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='measured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_measurements', to=settings.AUTH_USER_MODEL, verbose_name='Medido por'),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='route_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='assembly.assemblyroutestep', verbose_name='Paso de ruta'),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='assembly.assemblystation', verbose_name='Estacion'),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='station_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='assembly.unitstationevent', verbose_name='Evento de estacion'),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='assembly.serializedunit', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='assembly.plant', verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='assembly.assembledproduct', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='assembly.productversion', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plans', to='assembly.productionorder', verbose_name='Orden de produccion'),
        ),
        migrations.AddField(
            model_name='serializedunit',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='assembly.productionorder', verbose_name='Orden de produccion'),
        ),
        migrations.AddField(
            model_name='routestepparameter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routestepparameter',
            name='route_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='assembly.assemblyroutestep', verbose_name='Paso de ruta'),
        ),
        migrations.AddField(
            model_name='routestepparameter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionmeasurement',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='assembly.routestepparameter', verbose_name='Parametro'),
        ),
        migrations.AddConstraint(
            model_name='plantarea',
            constraint=models.UniqueConstraint(fields=('plant', 'code'), name='plant_area_plant_code_uq'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', 'due_date'], name='prod_order_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['product', 'status'], name='prod_order_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='routestepparameter',
            index=models.Index(fields=['code'], name='route_param_code_idx'),
        ),
        migrations.AddIndex(
            model_name='routestepparameter',
            index=models.Index(fields=['is_active'], name='route_param_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestepparameter',
            constraint=models.UniqueConstraint(fields=('route_step', 'code'), name='route_param_step_code_uq'),
        ),
        migrations.AddIndex(
            model_name='productionmeasurement',
            index=models.Index(fields=['unit', 'measured_at'], name='measurement_unit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmeasurement',
            index=models.Index(fields=['station', 'result'], name='measurement_station_result_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmeasurement',
            index=models.Index(fields=['code', 'measured_at'], name='measurement_code_time_idx'),
        ),
    ]
